sudo: false
language: node_js
node_js:
  - lts/*
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TRAVIS_COMMIT_MSG="[deploy] $(git log --format='%h - %B' --no-merges -n 1)"
- export TRAVIS_COMMIT_USER="$(git log --no-merges -n 1 --format=%an)"
- export TRAVIS_COMMIT_EMAIL="$(git log --no-merges -n 1 --format=%ae)"
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master