sudo: false
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  email: develop@lingtal.com
  committer_from_gh: true
  on:
    branch: master